[general]
import = [
  "catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[terminal]
shell = { program = "wsl", args = ["--cd", "/home/magnus/"] }


[font]  
normal = { family = "JetBrainsMono Nerd Font" }
size = 16

[cursor]
style = { shape = "Beam", blinking = "On" }
